roles:
  - name: geerlingguy.java
    java_packages:
     openjdk-8-jre-headless
     
  - name: geerlingguy.apache
    apache_create_vhosts: no 
    apache_mods_enabled: ["proxy.load", "proxy_http.load", "headers.load", "ssl.load", "rewrite.load"]
    apache_remove_default_vhost: true
    tags: ["geerlingguy.apache"] 
    
  - name: ansible-thoteam.nexus3-oss
    tags: ['ansible-thoteam.nexus3-oss']
    

collections:
  - name: awx.awx
  
  - name: community.postgresql
    src:  git@github.com:ansible-collections/community.postgresql.git
    scm:  git

  - name: community.docker
    src: git@github.com:ansible-collections/community.docker.git
    scm: git
#    version: 3.4.11

