- name: Nexus install and configure
  hosts: 34.0.39.110
  become: yes
  # tasks:
  #   # - name: copy certificate file
  #   #   ansible.builtin.copy:
  #   #     src: "{{ vault_httpd_ssl_certificate_file }}"
  #   #     dest: "{{ vault_httpd_ssl_certificate_file }}"
  #   # - name: copy key file
  #   #   ansible.builtin.copy:
  #   #     src: "{{ vault_httpd_ssl_certificate_key_file }}"
  #   #     dest: "{{ vault_httpd_ssl_certificate_key_file }}"


  vars:
    nexus_upgrade: true
    nexus_admin_password: "{{ vault_nexus_admin_password }}"
    nexus_public_hostname: 'nexus.vm'
    nexus_public_scheme: https
    httpd_setup_enable: true
    httpd_copy_ssl_files: false
    httpd_ssl_certificate_file: "{{ vault_httpd_ssl_certificate_file }}"
    httpd_ssl_certificate_key_file: "{{ vault_httpd_ssl_certificate_key_file }}"
    nexus_delete_default_repos: true
    

    nexus_local_users:
      - username: jenkins # used as key to update
        first_name: Jenkins
        last_name: CI
        email: support@company.com
        password: "{{ jenkins_pass }}"

    nexus_blobstores:
      - name: docker-images
        path: /var/nexus/blobs/docker-images
    nexus_repos_docker_hosted: 
      - name: team-greeen-docker-repo
        write_policy: allow
        blob_store: docker-images
    nexus_docker_bearer_token_realm: true



  roles:
    - { role: geerlingguy.java, java_packages: openjdk-8-jre-headless }
    - { role: geerlingguy.apache, apache_create_vhosts: no, apache_mods_enabled: ["proxy.load", "proxy_http.load", "headers.load", "ssl.load", "rewrite.load"], apache_remove_default_vhost: true, tags: ["geerlingguy.apache"] }
    - { role: ansible-thoteam.nexus3-oss, tags: ['ansible-thoteam.nexus3-oss'] }
