---
- name: For Production. Run Application in Docker TOM Cat.
  hosts: prod
  become: true
  vars:
    APP_IMAGE_TAG: latest

  tasks:
    - name: Ping server - Check Connection
      ping:

    - name: Pull Docker image
      docker_image:
        name: "{{ APP_IMAGE }}"
        source: pull

    - name: Create a volume
      docker_volume:
        name: mongo_volume

    - name: Create a network
      docker_network:
        name: network_prod

    - name: Run Redis Container
      docker_container:
        name: redis
        image: redis:7-alpine
        state: started
        restart: yes
        restart_policy: "always"
        networks:
          - name: network_prod
#        ports:
#          - "6379:6379"

    - name: Run Mongo Container
      docker_container:
        name: mongo
        image: mongo:7.0-rc-jammy
        state: started
        restart: yes
        restart_policy: "always"
        networks:
          - name: network_prod
        volumes:
          - mongo_volume

    - name: Run APP Tomcat container
      docker_container:
        name: app_container
        image: "{{ APP_IMAGE }}"
        state: started
        restart: yes
        restart_policy: "always"
        networks:
          - name: network_prod
        ports:
          - "{{ APP_PORT }}:8080"
        env:
          PG_CONTAINER_NAME: "{{ PG_CONTAINER_NAME }}"
          USER_NAME: "{{ PG_USERNAME }}"
          USER_PASS: "{{ PG_PASSWORD }}"
          PG_PORT:   "{{ PG_PORT }}"
          PG_DB_NAME: "{{ PG_DB_NAME }}"
          REDIS_CONTAINER_NAME: "{{ REDIS_CONTAINER_NAME }}"
          REDIS_PORT: "{{ REDIS_PORT }}" 
          MONGO_CONTAINER_NAME: "{{ MONGO_CONTAINER_NAME }}"
          MONGO_PORT: "{{ MONGO_PORT }}" 
          MONGO_DB_NAME: "{{ MONGO_DB_NAME }}"
