---
- name: Build and Push Docker image to Docker Hub
  hosts: build
  become: true
  gather_facts: false
  vars:
    APP_PATH: "/opt/java-app/"
    
  tasks:
    - name: Ensure Git is installed
      package:
        name: git
        state: present

    - name: Clone the repository
      git:
        repo: "{{ GIT_REPO }}"
        dest: "{{ APP_PATH }}"
        version: "{{ GIT_BRANCH }}" 
        
    - name: Log into Nexus
      docker_login:
        registry_url: "{{ NEXUS_HOSTNAME }}"
        username: "{{ NEXUS_USERNAME }}"
        password: "{{ NEXUS_PASSWORD }}"

    - name: Build and Push Docker image to Nexus Registry
      docker_image:
        name: "{{ NEXUS_HOSTNAME }}/{{ IMAGE_NAME }}"
        tag: "{{ IMAGE_TAG }}"
        repository: "{{ NEXUS_HOSTNAME }}/{{ IMAGE_NAME }}"
        build:
          path: "{{ APP_PATH }}"
          nocache: true
        push: true
        force_tag: true
        source: build   
        
    - name: Prune everything
      docker_prune:
        containers: true
        images: true
        images_filters:
          dangling: false
        networks: true
        volumes: true
        builder_cache: true
      
