---
- name: Run Application with Docker Compose
  hosts: stage_host
  become: true
  vars:
    APP_PATH: "/opt/java-app"
    GIT_REPO: "{{ GIT_REPO }}"
    PG_DUMP_FILE: "/opt/java-app/backup/2023-09-07.dump"

  tasks:
    - name: Ping server - Check Connection
      ping:

    - name: Ensure Git is installed
      package:
        name: git
        state: present

    - name: Clone the Git repository
      git:
        repo: "{{ GIT_REPO }}"
        dest: "{{ APP_PATH }}"
        version: "ansible" 

    - name: Tear down existing services
      docker_compose:
        project_src: "{{ APP_PATH }}"
        state: absent

    - name: Create and start services
      docker_compose:
        project_src: "{{ APP_PATH }}"
      register: output
      environment: 
          PG_CONTAINER_NAME: "postgresql"
          USER_NAME: "{{ PG_USERNAME }}"
          USER_PASS: "{{ PG_PASSWORD }}"
          PG_DB_NAME: "schedule"
          DH_REPO: "{{ DH_REPO }}"
          MONGO_DB_NAME: "schedules"
          MONGO_CONTAINER_NAME: "mongodb"
          REDIS_CONTAINER_NAME: "redis"

    - name: Restore PG data from file
      shell: |
        docker cp /opt/java-app/backup/2023-09-07.dump postgresql:/tmp/backup.dump
        docker exec -it postgresql psql -U "{{ PG_USERNAME }}" -d "schedule" -f /tmp/backup.dump

    - name: Show results
      ansible.builtin.debug:
        var: output
  
