---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "schedule-app"
  namespace: "app"
  labels:
    app: "schedule-app"
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: "schedule-app"
  template:
    metadata:
      labels:
        app: "schedule-app"
    spec:
      containers:
      - name: "backend"
        image: "stratiiv/devops-team-green:latest"
        ports: 
        - containerPort: 8080
        env:
        - name: "PG_HOST"
          value: "10.254.81.3"
        - name: "PG_PORT"
          value: "5432"
        - name: "PG_DB_NAME"
          value: "postgres"
        - name: "PG_USER"
          valueFrom:
            secretKeyRef:
              name: pg-user-pass
              key: username
        - name: "PG_PASS"      
          valueFrom:
            secretKeyRef:
              name: pg-user-pass
              key: password
        - name: "REDIS_HOST"
          value: "localhost"
        - name: "REDIS_PORT"
          value: "6379"
        - name: "MONGO_HOST"
          value: "localhost"
        - name: "MONGO_PORT"
          value: "27017"
        - name: "MONGO_DB_NAME"
          value: "schedule"

      - name: "redis"
        image: "redis:7-alpine"

---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "schedule-app-service"
  namespace: "app"
  labels:
    app: "schedule-app"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  selector:
    app: "schedule-app"
  type: "LoadBalancer"


                  
